INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (1,9300.0,'celular samsung',9700.0,1);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (2,8400.0,'celular nokia',8800.0,1);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (3,9500.0,'celular motorola',9900.0,1);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (4,16000.0,'mesa ratona',17000.0,2);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (5,27000.0,'mesa comedor',29000.0,2);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (6,16000.0,'silla',17000.0,2);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (7,9500.0,'mesa arrime',9800.0,2);

INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (8,20.0,'fideos de gluten',70.0,3);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (9,40.0,'arroz',70.0,3);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (10,100.0,'milanesas',250.0,3);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (11,100.0,'cerveza importada',150.0,4);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (12,1500.0,'manteca importada',290.0,4);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (13,50.0,'detergente',100.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (14,100.0,'skip',250.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (15,50.0,'ciff',150.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (16,400.0,'pelota futbol',800.0,6);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (17,50.0,'bagley chocolate',90.0,7);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (18,30.0,'bagley vainilla',70.0,7);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (19,100.0,'frutigran',150.0,7);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (20,20.0,'salvado',100.0,7);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (21,80.0,'libre de gluten',180.0,7);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (22,90.0,'pepsi',100.0,8);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (23,1800.0,'juego cubiertos 24',2000.0,9);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (24,2800.0,'juego cubiertos 42',3000.0,9);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (25,1600.0,'juego platos',1700.0,10);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (26,1700.0,'bolsa caramelos 500',1900.0,11);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (27,3800.0,'bolsa caramelos 1000',4000.0,11);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (28,75.0,'jabon ropa',80.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (29,30.0,'rejijlla',70.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (30,100.0,'poet',150.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (31,850.0,'lavandina',900.0,5);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (32,2600.0,'muñeca barby',2700.0,6);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (33,3700.0,'muñeca malibu',3900.0,6);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (34,3600.0,'camion juguete',3700.0,6);
INSERT INTO ventaonline.Product(id,costprice,name,saleprice,tipoProducto_id) VALUES (35,500.0,'auto juguete',550.0,6);